"""Generate the LaTeX tables and the macro definitions the paper reads at build time.

The paper is forbidden from containing a hard-coded number. Every quantity it cites is
defined here as a macro in ``results/macros.tex``, and every table it includes is written
here as a ``booktabs`` fragment in ``results/tables``. If an analysis has not been run,
the macro it would have produced is absent, the paper fails to compile, and the
inconsistency is caught rather than published.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pandas as pd

import config
from src import features as F

# --------------------------------------------------------------------------------------
# Loading and lookup
# --------------------------------------------------------------------------------------

_MISSING = object()


def load(name: str) -> dict | None:
    """Read a metrics file, returning None when the producing stage has not run."""
    path = config.METRICS / f"{name}.json"
    if not path.exists():
        return None
    return json.loads(path.read_text())


def load_results(name: str) -> dict | None:
    path = config.RESULTS / f"{name}.json"
    if not path.exists():
        return None
    return json.loads(path.read_text())


def dig(obj: Any, *path: str | int, default: Any = _MISSING) -> Any:
    """Walk a nested structure, tolerating absent branches."""
    cur = obj
    for key in path:
        if cur is None:
            break
        try:
            cur = cur[key]
        except (KeyError, IndexError, TypeError):
            cur = None
            break
    if cur is None:
        if default is _MISSING:
            return None
        return default
    return cur


# --------------------------------------------------------------------------------------
# Formatting
# --------------------------------------------------------------------------------------

_TEX_ESCAPES = {
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


def tex_escape(text: Any) -> str:
    out = []
    for ch in str(text):
        out.append(_TEX_ESCAPES.get(ch, ch))
    return "".join(out)


def num(value: Any, places: int = 3) -> str:
    """Format a number for the text. Integers stay integers."""
    if value is None:
        return "n/a"
    if isinstance(value, bool):
        return "yes" if value else "no"
    if isinstance(value, int):
        return f"{value:,}"
    try:
        f = float(value)
    except (TypeError, ValueError):
        return tex_escape(value)
    if f.is_integer() and abs(f) < 1e6:
        return f"{int(f):,}"
    return f"{f:.{places}f}"


def pct(value: Any, places: int = 1) -> str:
    """Format a fraction in 0..1 as a percentage number, without the sign."""
    if value is None:
        return "n/a"
    f = float(value)
    if f <= 1.0:
        f *= 100.0
    return f"{f:.{places}f}"


# --------------------------------------------------------------------------------------
# Macro emission
# --------------------------------------------------------------------------------------


class Macros:
    """Collects macro definitions and writes them once, checking for collisions."""

    def __init__(self) -> None:
        self._defs: dict[str, str] = {}
        self._skipped: list[str] = []

    def add(self, name: str, value: Any, places: int = 3) -> None:
        if value is None:
            self._skipped.append(name)
            return
        self._defs[name] = num(value, places) if not isinstance(value, str) else tex_escape(value)

    def add_pct(self, name: str, value: Any, places: int = 1) -> None:
        if value is None:
            self._skipped.append(name)
            return
        self._defs[name] = pct(value, places)

    def add_raw(self, name: str, text: str) -> None:
        self._defs[name] = text

    @property
    def skipped(self) -> list[str]:
        return sorted(self._skipped)

    def write(self, path: Path) -> int:
        lines = [
            "% Generated by src/tables.py. Do not edit by hand.",
            "% Every number cited by the paper is defined here.",
            "",
        ]
        for name in sorted(self._defs):
            lines.append(f"\\newcommand{{\\{name}}}{{{self._defs[name]}}}")
        lines.append("")
        path.write_text("\n".join(lines))
        return len(self._defs)


# --------------------------------------------------------------------------------------
# Table writers
# --------------------------------------------------------------------------------------


def _write_table(name: str, body: str) -> Path:
    path = config.TABLES / f"{name}.tex"
    path.write_text(body.rstrip() + "\n")
    return path


def table_data_availability(keeper_avail: dict | None) -> None:
    """Non-null column counts per raw table, the evidence for the withdrawal claim."""
    rows = []
    for season in config.SEASONS:
        season_dir = config.DATA_RAW / season
        for stat in config.PLAYER_STAT_TYPES:
            path = season_dir / f"players_{stat}.parquet"
            if not path.exists():
                continue
            df = pd.read_parquet(path)
            ids = {"league", "season", "team", "player", "nation", "pos", "age", "born"}
            cols = [c for c in df.columns if c not in ids]
            empty = sum(1 for c in cols if df[c].notna().sum() == 0)
            rows.append(
                {
                    "season": season,
                    "table": stat.replace("_", " "),
                    "stat_cols": len(cols),
                    "empty": empty,
                    "usable": len(cols) - empty,
                }
            )
    if not rows:
        return
    df = pd.DataFrame(rows)
    primary = df[df.season == config.SEASON_PRIMARY]
    repl = df[df.season == config.SEASON_REPLICATION].set_index("table")

    lines = [
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\caption{Populated columns in each FBref player table. The tables are still "
        r"served with complete headers, so the empty counts are the number of columns "
        r"that resolve correctly and contain no values.}",
        r"\label{tab:availability}",
        r"\begin{tabular}{lrrrr}",
        r"\toprule",
        r" & \multicolumn{2}{c}{"
        + config.SEASON_PRIMARY
        + r"} & \multicolumn{2}{c}{"
        + config.SEASON_REPLICATION
        + r"} \\",
        r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}",
        r"Table & Columns & Empty & Columns & Empty \\",
        r"\midrule",
    ]
    for _, r in primary.iterrows():
        other = repl.loc[r["table"]] if r["table"] in repl.index else None
        o_cols = int(other["stat_cols"]) if other is not None else 0
        o_empty = int(other["empty"]) if other is not None else 0
        lines.append(
            f"{tex_escape(r['table'])} & {r['stat_cols']} & {r['empty']} & {o_cols} & {o_empty} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    _write_table("data_availability", "\n".join(lines))


def table_feature_dictionary() -> None:
    """The full outfield feature set with its source and definition."""
    definitions = {
        "np_xg_p90": ("Understat", "Non-penalty expected goals"),
        "xa_p90": ("Understat", "Expected assists"),
        "key_passes_p90": ("Understat", "Passes leading directly to a shot"),
        "xg_chain_p90": ("Understat", "Expected goals of possessions the player was involved in"),
        "xg_buildup_p90": ("Understat", "As xGChain, excluding shots and key passes"),
        "shots_p90": ("FBref", "Shots taken, excluding penalties"),
        "shots_on_target_p90": ("FBref", "Shots on target"),
        "goals_non_penalty_p90": ("FBref", "Goals excluding penalties"),
        "assists_p90": ("FBref", "Assists"),
        "crosses_p90": ("FBref", "Crosses attempted"),
        "interceptions_p90": ("FBref", "Interceptions"),
        "tackles_won_p90": ("FBref", "Tackles won"),
        "fouls_committed_p90": ("FBref", "Fouls committed"),
        "fouls_drawn_p90": ("FBref", "Fouls drawn"),
        "offsides_p90": ("FBref", "Times caught offside"),
        "cards_yellow_p90": ("FBref", "Yellow cards"),
        "shot_accuracy_pct": ("FBref", "Shots on target as a share of shots, a rate"),
        "goals_per_shot": ("FBref", "Goals per shot, a rate"),
    }
    lines = [
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\caption{The outfield feature set. Counting statistics are per ninety minutes. "
        r"The two rate features are used as published.}",
        r"\label{tab:features}",
        r"\begin{tabular}{llp{7.2cm}}",
        r"\toprule",
        r"Feature & Source & Definition \\",
        r"\midrule",
    ]
    for feat in F.OUTFIELD_CORE:
        source, definition = definitions.get(feat, ("", ""))
        lines.append(f"{tex_escape(feat)} & {source} & {definition} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    _write_table("feature_dictionary", "\n".join(lines))


def table_umap_grid(grid: dict | None) -> None:
    if not grid:
        return
    season = dig(grid, config.SEASON_PRIMARY) or grid
    entries = None
    for key in ("grid", "results", "configurations"):
        if isinstance(season, dict) and key in season:
            entries = season[key]
            break
    if entries is None and isinstance(season, list):
        entries = season
    if not entries:
        return

    rows = []
    for e in entries:
        if not isinstance(e, dict):
            continue
        rows.append(
            {
                "n": e.get("n_neighbors", e.get("n_neighbours")),
                "d": e.get("min_dist"),
                "t": e.get("trustworthiness"),
            }
        )
    rows = [r for r in rows if r["n"] is not None and r["t"] is not None]
    if not rows:
        return
    rows.sort(key=lambda r: -float(r["t"]))

    lines = [
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\caption{UMAP hyperparameter grid, ranked by trustworthiness. Selection was by "
        r"trustworthiness alone and was decided before any embedding was inspected.}",
        r"\label{tab:umapgrid}",
        r"\begin{tabular}{rrr}",
        r"\toprule",
        r"Neighbours & Minimum distance & Trustworthiness \\",
        r"\midrule",
    ]
    for r in rows:
        lines.append(f"{int(r['n'])} & {num(r['d'], 2)} & {num(r['t'], 4)} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    _write_table("umap_grid", "\n".join(lines))


def table_divergence(div: dict | None) -> None:
    if not div:
        return
    season = dig(div, config.SEASON_PRIMARY)
    top = None
    for key in ("top_divergent", "top10", "top_pairs"):
        if isinstance(season, dict) and key in season:
            top = season[key]
            break
    if not top:
        return
    lines = [
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\caption{The ten feature pairs whose Spearman correlation differs most across "
        r"position groups. Every pair changes sign between at least two groups.}",
        r"\label{tab:divergence}",
        r"\begin{tabular}{llrrrr}",
        r"\toprule",
        r"Feature A & Feature B & DF & MF & FW & Spread \\",
        r"\midrule",
    ]
    for r in top[:10]:
        g = r.get("by_group", {})
        lines.append(
            f"{tex_escape(r.get('label_a', r.get('feature_a')))} & "
            f"{tex_escape(r.get('label_b', r.get('feature_b')))} & "
            f"{num(g.get('DF'), 2)} & {num(g.get('MF'), 2)} & {num(g.get('FW'), 2)} & "
            f"{num(r.get('spread'), 2)} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    _write_table("correlation_divergence", "\n".join(lines))


def table_summary_by_position(summary: dict | None) -> None:
    if not summary:
        return
    season = dig(summary, config.SEASON_PRIMARY)
    groups = dig(season, "groups")
    if not groups:
        return
    metrics = F.HEADLINE_METRICS
    lines = [
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\caption{Headline per-90 statistics by position group in the primary season, "
        r"reported as mean with standard deviation in parentheses.}",
        r"\label{tab:summary}",
        r"\begin{tabular}{lrrr}",
        r"\toprule",
        r"Statistic & DF & MF & FW \\",
        r"\midrule",
    ]
    for m in metrics:
        cells = []
        for grp in ("DF", "MF", "FW"):
            stats = dig(groups, grp, m) or {}
            mean, sd = stats.get("mean"), stats.get("std", stats.get("sd"))
            cells.append(f"{num(mean, 2)} ({num(sd, 2)})" if mean is not None else "n/a")
        lines.append(f"{tex_escape(m)} & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    _write_table("summary_by_position", "\n".join(lines))


def table_k_selection(sel: dict | None) -> None:
    if not sel:
        return
    season = dig(sel, "seasons", config.SEASON_PRIMARY)
    if not season:
        return
    lines = [
        r"\begin{longtable}{llrrrrr}",
        r"\caption{Cluster selection criteria for every candidate number of clusters, by "
        r"scope. The consensus rule is applied to these values.}\\",
        r"\label{tab:kselection}\\",
        r"\toprule",
        r"Scope & $k$ & Silhouette & Davies-Bouldin & Calinski-Harabasz & Gap \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"Scope & $k$ & Silhouette & Davies-Bouldin & Calinski-Harabasz & Gap \\",
        r"\midrule",
        r"\endhead",
    ]
    wrote = False
    for scope in ("global", "DF", "MF", "FW"):
        curves = dig(season, scope, "spaces", "standardised", "curves")
        if not isinstance(curves, dict):
            continue
        chosen = dig(season, scope, "chosen_k")
        # curves is {criterion: {k: value}}, so pivot on the k keys of the silhouette curve.
        for k in sorted(curves.get("silhouette", {}), key=int):
            mark = r"$\ast$" if str(chosen) == str(k) else ""
            lines.append(
                f"{scope}{mark} & {k} & "
                f"{num(dig(curves, 'silhouette', k), 3)} & "
                f"{num(dig(curves, 'davies_bouldin', k), 3)} & "
                f"{num(dig(curves, 'calinski_harabasz', k), 1)} & "
                f"{num(dig(curves, 'gap', k), 3)} \\\\"
            )
            wrote = True
    lines += [r"\bottomrule", r"\end{longtable}"]
    if wrote:
        _write_table("k_selection", "\n".join(lines))


def table_cluster_membership() -> None:
    """Every eligible player with club, listed position, archetype and centroid distance."""
    path = config.DATA_PROCESSED / f"archetypes_{config.SEASON_PRIMARY}.parquet"
    if not path.exists():
        return
    df = pd.read_parquet(path).sort_values(["position_group", "archetype_name", "player"])
    lines = [
        r"\begin{longtable}{llllr}",
        r"\caption{Cluster membership for every eligible outfield player in the primary "
        r"season.}\\",
        r"\label{tab:membership}\\",
        r"\toprule",
        r"Player & Club & Listed & Archetype & Distance \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"Player & Club & Listed & Archetype & Distance \\",
        r"\midrule",
        r"\endhead",
    ]
    for _, r in df.iterrows():
        lines.append(
            f"{tex_escape(r['player'])} & {tex_escape(r['team'])} & "
            f"{tex_escape(r['position_group'])} & {tex_escape(r['archetype_name'])} & "
            f"{num(r.get('distance_to_centroid'), 2)} \\\\"
        )
    lines += [r"\bottomrule", r"\end{longtable}"]
    _write_table("cluster_membership", "\n".join(lines))


def table_minutes_sensitivity(pre: dict | None, sens: dict | None) -> None:
    """Eligible counts and, when available, clustering outcomes at each threshold."""
    if not pre:
        return
    counts = dig(pre, config.SEASON_PRIMARY, "minutes_sensitivity_counts") or {}
    if not counts:
        return
    lines = [
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\caption{Sensitivity of the analysis to the minutes threshold in the primary "
        r"season.}",
        r"\label{tab:sensitivity}",
        r"\begin{tabular}{rrrrr}",
        r"\toprule",
        r"Minutes & Eligible & $k$ & Silhouette & Bootstrap ARI \\",
        r"\midrule",
    ]
    for threshold in config.MIN_MINUTES_SENSITIVITY:
        row = dig(sens, str(threshold)) or {}
        lines.append(
            f"{threshold} & {counts.get(str(threshold), 'n/a')} & "
            f"{row.get('k', 'n/a')} & {num(row.get('silhouette'), 3)} & "
            f"{num(row.get('bootstrap_ari'), 3)} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    _write_table("minutes_sensitivity", "\n".join(lines))


# --------------------------------------------------------------------------------------
# Macro assembly
# --------------------------------------------------------------------------------------


def build_macros() -> Macros:
    m = Macros()
    pre = load("preprocess")
    norm = load("normality")
    div = load("correlation_divergence")
    emb = load("embedding_comparison")
    grid = load("umap_grid")
    pca = load("pca_loadings")
    sel = load("cluster_selection")
    stab = load("cluster_stability")
    vspos = load("cluster_vs_position")
    keep_avail = load("keeper_data_availability")

    primary, repl = config.SEASON_PRIMARY, config.SEASON_REPLICATION

    m.add_raw("SeasonPrimary", primary)
    m.add_raw("SeasonReplication", repl)
    m.add("MinMinutes", config.MIN_MINUTES)
    m.add("NFeatures", len(F.OUTFIELD_CORE))
    m.add("BootstrapN", config.BOOTSTRAP_N)
    m.add("GapB", config.GAP_STATISTIC_B)

    # Population
    m.add("NPlayersRawPrimary", dig(pre, primary, "understat_match", "fbref_rows"))
    m.add("NPlayersRawRepl", dig(pre, repl, "understat_match", "fbref_rows"))
    m.add("NOutfieldPrimary", dig(pre, primary, "rows_outfield"))
    m.add("NEligiblePrimary", dig(pre, primary, "rows_outfield_eligible"))
    m.add("NEligibleRepl", dig(pre, repl, "rows_outfield_eligible"))
    m.add("NKeepersPrimary", dig(pre, primary, "rows_keepers"))
    m.add("NKeepersRepl", dig(pre, repl, "rows_keepers"))
    m.add("NMultiClubPrimary", dig(pre, primary, "players_multi_club"))
    for grp in ("DF", "MF", "FW"):
        m.add(f"N{grp}Primary", dig(pre, primary, "position_group_counts", grp))
    m.add_pct("MatchRatePrimary", dig(pre, primary, "understat_match", "match_rate"))
    m.add_pct("MatchRateRepl", dig(pre, repl, "understat_match", "match_rate"))

    # Normality
    m.add("NFeaturesRejectNormal", dig(norm, primary, "n_features_rejecting_normality_shapiro_005"))
    m.add("SkewMeanAbs", dig(norm, primary, "skew_mean_abs"), places=2)
    m.add("SkewMax", dig(norm, primary, "skew_max"), places=2)
    m.add_raw("SkewMaxFeature", tex_escape(dig(norm, primary, "skew_max_feature") or ""))

    # Correlation divergence
    m.add("CorrSpreadMax", dig(div, primary, "spread_max"), places=2)
    m.add("CorrSpreadMedian", dig(div, primary, "spread_median"), places=2)

    # Embeddings
    for key, macro in (("pca", "PCA"), ("umap", "UMAP"), ("tsne", "TSNE")):
        block = dig(emb, primary, "embeddings", key) or {}
        m.add(f"Trust{macro}", block.get("trustworthiness"), places=3)
        m.add(f"Cont{macro}", block.get("continuity"), places=3)
        m.add(f"Purity{macro}", block.get("knn_position_purity"), places=3)
    m.add("PurityBaseline", dig(emb, primary, "purity_baseline_random"), places=3)
    m.add("KNNPurityK", dig(emb, primary, "k"))

    best = dig(grid, primary, "best") or {}
    m.add("UMAPBestNeighbors", best.get("n_neighbors"))
    m.add("UMAPBestMinDist", best.get("min_dist"), places=2)
    m.add("UMAPBestTrust", dig(grid, primary, "best_trustworthiness"), places=4)
    span = dig(grid, primary, "trustworthiness_range")
    if isinstance(span, list | tuple) and len(span) == 2:
        m.add("UMAPTrustMin", span[0], places=4)
        m.add("UMAPTrustMax", span[1], places=4)

    # PCA variance
    for i in range(1, 4):
        m.add(
            f"PCVar{['One', 'Two', 'Three'][i - 1]}",
            dig(pca, primary, "explained_variance_ratio", i - 1),
            places=3,
        )

    # Clustering
    for scope in ("global", "DF", "MF", "FW"):
        label = "Global" if scope == "global" else scope
        m.add(f"K{label}", dig(sel, "seasons", primary, scope, "chosen_k"))
        m.add(f"BootARI{label}", dig(stab, "seasons", primary, scope, "ari_mean"), places=3)
        m.add(f"BootARISD{label}", dig(stab, "seasons", primary, scope, "ari_sd"), places=3)
        m.add(f"BootARIMin{label}", dig(stab, "seasons", primary, scope, "ari_min"), places=3)
    m.add("ARIvsPosition", dig(vspos, "answer", "adjusted_rand_index_vs_position_group"), places=3)
    m.add("PurityVsPosition", dig(vspos, "answer", "cluster_purity_vs_position_group"), places=3)

    # Goalkeeper availability
    m.add("NKeeperAdvEmpty", dig(keep_avail, "summary", "keeper_adv_all_null", primary))
    m.add("NKeeperAdvStatCols", dig(keep_avail, "summary", "keeper_adv_stat_columns", primary))
    m.add("NKeeperAdvUsable", dig(keep_avail, "summary", "keeper_adv_usable", primary))

    return m


def main() -> None:
    config.TABLES.mkdir(parents=True, exist_ok=True)

    table_data_availability(load("keeper_data_availability"))
    table_feature_dictionary()
    table_umap_grid(load("umap_grid"))
    table_divergence(load("correlation_divergence"))
    table_summary_by_position(load("descriptive_summary"))
    table_k_selection(load("cluster_selection"))
    table_cluster_membership()
    table_minutes_sensitivity(load("preprocess"), load("minutes_sensitivity"))

    macros = build_macros()
    count = macros.write(config.RESULTS / "macros.tex")

    written = sorted(p.name for p in config.TABLES.glob("*.tex"))
    print(f"wrote {count} macros to results/macros.tex")
    print(f"wrote {len(written)} tables: {', '.join(written)}")
    if macros.skipped:
        print(f"macros skipped because their metrics are absent: {', '.join(macros.skipped)}")


if __name__ == "__main__":
    main()
